### ISSUE TITLE
Add Windows & bare-metal support.

### ISSUE THREAD

**Issue by lygstate** [redox-os/relibc#107]

**Comment by ids1024** [comment]
Would bare metal support largely consist of disabling OS related functions (`open` can't do anything without an OS, etc)?

The memory allocator would also have to not request memory from the OS.

**Comment by lygstate** [comment]
In align with https://github.com/rust-lang-nursery/portability-wg/issues/1#issuecomment-375912595

**Comment by jackpot51** [comment]
We likely will not add Windows support. It is too different of a platform to make that possible.

**Comment by lygstate** [comment]
newlib support forWindows

**Comment by BearzRobotics** [comment]
The thing is this is not trying to become a general c library. Its only goal is to allow c programs to compile on redox.

**Comment by MggMuggins** [comment]
*C programs written for unix
