### ISSUE TITLE
Create a rustfmt.toml and add to CI

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/relibc#17]
A code style should be picked and a `rustfmt.toml` should be generated for this project. Then we should add a line to the `.travis.yml` script with something like the following.

```
 - cargo fmt -- --write-mode=diff 
```

**NB**: There are a few things that make this a bit more difficult than running `cargo fmt` at the moment.

  - A submodule e.g. `cbindgen`, `ralloc`, or `va_list` may not be formatted the same as this project.
  - We currently visually align constants. AFAIK there is not a way to make rustfmt do this.

**Comment by jackpot51** [comment]
I agree strongly with this. We can take the rustfmt.toml from ion, for example

**Comment by dlrobertson** [comment]
> We can take the rustfmt.toml from ion

The rustfmt.toml for ion is the legacy format. Should we be using `rustfmt-nightly` or the old `rustfmt`?

**Comment by jackpot51** [comment]
I would like to use the new format then

**Comment by dlrobertson** [comment]
:+1: I'll try to make it similar to what ion uses though

**Comment by jackpot51** [comment]
Thanks!

**Comment by dlrobertson** [comment]
Part of the first pass was added to #16

**Comment by dlrobertson** [comment]
Due to the dependencies being submodules, a second follow-up PR will need to be made to add the style check to CI.

**Comment by dlrobertson** [comment]
Fixed by #20
