### ISSUE TITLE
fcntl: implement the fcntl function

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/relibc#36]
The `fcntl` function is currently unimplemented. Both linux and redox support the fcntl syscall.

relevant files:
 - `src/fcntl/src/lib.rs`: Generic platform independent code
 - `src/platform/<os>/lib.rs`: Platform dependent wrapper around the syscall

spec:
 - http://pubs.opengroup.org/onlinepubs/7908799/xsh/fcntl.html

**Comment by MggMuggins** [comment]
I've implemented the function, but I'm giving up on tests for the time being because in order to write complete tests you almost _need_ a complete standard library...

So probably best not to close this issue until tests get written or #5 happens.

**Comment by MggMuggins** [comment]
#43 Includes a test, we can close this.

**Comment by dlrobertson** [comment]
Thanks!
