### ISSUE TITLE
wait: Implement waitpid

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/relibc#71]
`waitpid` has not been implemented. Redox has the `waitpid` syscall and linux has `WAIT4`. A low level platform specific wrapper for `waitpid` should be added to the `platform` crate, followed by a platform generic implementation written for the `wait` crate.

**Comment by sajattack** [comment]
I'm not sure how to write a test for this...

**Comment by dlrobertson** [comment]
We have `fork` implemented so it actually should be fairly easy.

```
if ((pid = fork()) == 0) {
    // child
    exit(0);
} else {
    // parent
    waitpid(pid, ...);
}
```

**Comment by sajattack** [comment]
wait and waitpid have been implemented and merged.
