### ISSUE TITLE
unistd: Implement getopt

### ISSUE THREAD

**Issue by dlrobertson** [redox-os/relibc#87]
The current implementation of [getopt] (in [src/unistd/src/lib.rs]) is unimplemented. It is needed to compile the `libc-test` `libtest.a`.

[src/unistd/src/lib.rs]: https://github.com/redox-os/relibc/blob/a1baf1c92df4681fba75e31489c26cc1babfe4c1/src/unistd/src/lib.rs#L208
[getopt]: http://pubs.opengroup.org/onlinepubs/009695399/functions/getopt.html

**Comment by Arcterus** [comment]
I’ve written an implementation of this and will submit a pull request once I finish testing.

**Comment by dlrobertson** [comment]
Fixed in: https://github.com/redox-os/relibc/pull/97
