### ISSUE TITLE
Safe vs Unsafe in library functions.

### ISSUE THREAD

**Issue by Tommoa** [redox-os/relibc#93]
Currently, almost all implemented library functions are marked as `unsafe`. Should we be aiming to make as many library functions "safe" (or as close to, we still need to work with raw pointers) as possible, or should everything just be left as `unsafe`?

**Comment by Arcterus** [comment]
If the safety of the function is entirely dependent on an input pointer being valid, I would say marking it `unsafe` is correct.  Frankly many of the functions are “unsafe” as passing an incorrect value will lead to undefined behavior.

**Comment by ids1024** [comment]
Yes, functions should be marked safe where appropriate. But any function that takes a raw pointer and dereferences it is unsafe (which probably applies to the majority of the C standard library).
